.gitignore
test/graaflib/graph_test.cpp

The pull request includes changes that augment the test coverage to `78.38%`, with a focus on the `graph_test` file.
The changes in the pull request encompass the following:
-    Addition of new test cases to cover  the graph module.
- Improvement of existing test cases to include edge cases and handle exceptions appropriately.
I have ensured that all tests pass successfully,

improve test covr

---

src/graaflib/algorithm/graph_traversal.h
src/graaflib/algorithm/graph_traversal.tpp
src/graaflib/directed_graph.h
src/graaflib/directed_graph.tpp
src/graaflib/graph.h
src/graaflib/graph.tpp
src/graaflib/types.cpp
src/graaflib/types.h
src/graaflib/undirected_graph.h
src/graaflib/undirected_graph.tpp
test/graaflib/graph_test.cpp

- Split implementation and definition in all headers
- Added missing includes
- Fixed some typos in javadoc

refactor: Split definition and implementation of graph classes

---

src/graaflib/algorithm/shortest_path.h
src/graaflib/algorithm/shortest_path.tpp
test/graaflib/algorithm/shortest_path_test.cpp

**Value add:**
- capabilities to calculate the shortest path between **one start** and **one end** vertex
- calculation for unweighted graphs; weighted graphs will be addressed in a follow-up PR

feat: Unweighted shortest path

---

include/graaflib/properties/vertex_properties.h
include/graaflib/properties/vertex_properties.tpp
test/graaflib/properties/vertex_properties_test.cpp

feat: Vertex degree [free function version]

---

examples/dot_serialization/main.cpp
examples/shortest_path/main.cpp
include/graaflib/algorithm/graph_traversal.h
include/graaflib/algorithm/graph_traversal.tpp
include/graaflib/algorithm/shortest_path.h
include/graaflib/algorithm/shortest_path.tpp
include/graaflib/directed_graph.h
include/graaflib/directed_graph.tpp
include/graaflib/graph.h
include/graaflib/graph.tpp
include/graaflib/io/dot.h
include/graaflib/io/dot.tpp
include/graaflib/properties/vertex_properties.h
include/graaflib/properties/vertex_properties.tpp
include/graaflib/types.h
include/graaflib/undirected_graph.h
include/graaflib/undirected_graph.tpp
test/graaflib/directed_graph_test.cpp
test/graaflib/graph_test.cpp
test/graaflib/graph_traits_test.cpp
test/graaflib/io/dot_test.cpp
test/graaflib/undirected_graph_test.cpp
test/graaflib/weighted_graph_test.cpp

- If an edge is unweighted, the user can simply not derive from `weighted_edge`.
- It is now also possible to derive from `weighted_edge` but not implement `get_weight`. In that case a default implementation is provided which always returns a unit weight.

Remove unweighted graph spec

---

include/graaflib/directed_graph.h
include/graaflib/directed_graph.tpp
include/graaflib/graph.h
include/graaflib/graph.tpp
include/graaflib/undirected_graph.h
include/graaflib/undirected_graph.tpp
test/graaflib/graph_test.cpp

Previously there was a bug where calling a getter (`get_edge` or `get_vertex`) on a `const` graph invoked an infinite recursion, resulting in a stack overflow. This is solved by calling const getters from within the non-const getters as per Effective C++ item 3. 
Since the member function calling it is non-const, the object itself is non-const, and casting away the const is allowed.

fix: stack overflow for const getters

---

examples/dot_serialization/main.cpp
include/graaflib/graph.h
include/graaflib/graph.tpp
perf/graaflib/add_edge_benchmark.cpp
perf/graaflib/add_vertex_benchmark.cpp
test/graaflib/io/dot_test.cpp

I did not measure any significant performance improvement when building in release mode. I expect the compiler is able to optimize the redundant move construction. Nevertheless, I think perfect forwarding is still a nice to have.

perf: perfect forwarding

---

.gitignore
tools/benchmark_visualization.py
tools/requirements.txt

This PR adds a python script under `tools/`, which can be used to visualize google benchmark data. An example plot can be found below.
Not very familiar with python, so any improvement suggestions are more than welcome.

tooling: Benchmark visualization script

---

docs/docs/examples/example-basics/shortest-path.md
examples/shortest_path/main.cpp
include/graaflib/algorithm/cycle_detection.h
include/graaflib/algorithm/cycle_detection.tpp
include/graaflib/algorithm/graph_traversal.h
include/graaflib/algorithm/graph_traversal.tpp
include/graaflib/algorithm/shortest_path.h
include/graaflib/algorithm/shortest_path.tpp
include/graaflib/properties/vertex_properties.h
include/graaflib/properties/vertex_properties.tpp
test/graaflib/algorithm/cycle_detection_test.cpp
test/graaflib/algorithm/graph_traversal_test.cpp
test/graaflib/algorithm/shortest_path_test.cpp
test/graaflib/properties/vertex_properties_test.cpp

Should be merged after #48 
This PR exposes the algorithm names to the user. For example, instead of calling `get_shortest_path`, the user now calls `dijkstra_shortest_path`. This should also make it easier to add new algorithms.

breaking-change: Expose algorith names to interface

---

include/graaflib/algorithm/shortest_path.h
include/graaflib/algorithm/shortest_path.tpp
test/graaflib/algorithm/shortest_path_test.cpp

Please note:
- This is not an exact overload of `dijkstra_shortest_path` as the syntax proposed in #54 uses the plural `paths`.
- There is quite some code duplication between the tree version and the non-tree version. The tree version would be able to cover both with an additional break statement, which is expected to have worse performance though. We could however think of trading some performance for readability and maintainability here.

[ALGO] Dijkstra Shortest Path (Tree Version) (#54)

---

include/graaflib/algorithm/graph_traversal.h
include/graaflib/algorithm/graph_traversal.tpp
test/graaflib/algorithm/graph_traversal_test.cpp

This PR addresses #63.
Instead of reporting the traversed vertices in `breadth_first_traverse` and `depth_first_traverse`, we report the traversed edges.
In a follow up I would make a similar change to the shortest path algorithms, as a path given by a range of edges is more usable. See our current shortest path example.

breaking-change: Report traversed edges instead of vertices

---

codecov.yml
include/graaflib/algorithm/graph_traversal.h
include/graaflib/algorithm/graph_traversal.tpp
include/graaflib/algorithm/shortest_path.tpp
test/graaflib/algorithm/graph_traversal_test.cpp
test/graaflib/algorithm/shortest_path_test.cpp

This PR does the following:
- Adds an optional `search_termination_strategy` to BFS and DFS
- Refactors `bfs_shortest_path` to make use of the existing `breadth_first_traverse`
- Fixes the expected path length in shortest path tests

breaking-change: Re-use graph traversal in bfs_shortest_path

---

include/graaflib/algorithm/shortest_path.tpp
test/graaflib/algorithm/shortest_path_test.cpp

Dijkstra's algorithm can't deal with negative edge weighs. Until now, we don't check this, which could lead to unexpected or misleading results. This PR fixes this by throwing an error on negative weights during the traversal.
The additional tests introduce some boilerplate code since we need to add a new type set that is purely signed. I'm open for feedback regarding more elegant ways to solve this!

Enhancement: Catch negative edge weights in dijkstra

---

include/graaflib/algorithm/shortest_path.tpp
test/graaflib/algorithm/shortest_path_test.cpp

Complementary to #67.
Note that I again used `std::format`, which I see to be removed in the whole codebase in a follow-up PR.

Enhancement: Catch negative edge weights in tree-version dijkstra

---

.Dockerignore
Dockerfile

In this PR, I've added a Dockerfile and .dockerignore to containerize the build process for the project.
Changes:
`Dockerfile:` This file sets up an Ubuntu 22.04 environment, installs necessary dependencies, and builds the project using CMake and Clang.
`.dockerignore:` To ensure only necessary files are copied into the Docker image and to exclude unnecessary files.

add dockerFile && Dockerignore

---

docs/docs/algorithms/traversal/breadth-first-search.md

Hello, I made the documentation for BFS.
Please Check the ## Syntax section. I understood not exactly what I did here.
Also I'm not sure with the content at ### BFS is particularly useful for: , because I not used this algorithms in praxis.
I have only experience with dijkstra in robot programming.

docs: add documentation for BFS (#56)

---

docs/docs/algorithms/traversal/depth-first-search.md

Hello, I am adding the documentation for DFS. #57 
It is quite the same as BFS, with a stack instead of a queue. 
Also the call is the same, except for the name, as far as I could see.
@bobluppes Sorry for the rebuild, I played a bit with git and did a rebase. somehow the old PR disappeared. #77

Doc (dfs) add documentation for DFS (#57)

---

include/graaflib/algorithm/shortest_path.tpp

do the string concatenation manually Issue:#72
@bobluppes @joweich  I created my own PR to see if the code would pass the test. I am new here and have no experience. I don't know if this is the right approach in this case. Perhaps you should delete this duplicate PR. #75

refactor:  Remove usage of fmt in library #72

---

README.md
docs/docs/algorithms/strongly-connected-components/_category_.json
docs/docs/algorithms/strongly-connected-components/tarjan.md
include/graaflib/algorithm/strongly_connected_components.h
include/graaflib/algorithm/strongly_connected_components.tpp
test/graaflib/algorithm/strongly_connected_components_test.cpp

See https://github.com/bobluppes/graaf/issues/53

Work on Tarjan's SCC algorithm

---

docs/docs/algorithms/shortest-path/bfs-based-shortest-path.md
include/graaflib/algorithm/shortest_path.h

Docs for BFS-based shortest path search

---

.github/dependabot.yml

I found this to be quite handy to keep gh actions up-to-date. We could think of extending it with checking cpp specific dependencies down the road as well.

[TOOL] Add Dependabot for GitHub actions

---

include/graaflib/algorithm/shortest_path.tpp
test/graaflib/algorithm/shortest_path_test.cpp

This PR solves the #76 issue.
I have added the code for detecting a Negative cycle in Bellman Ford Shortest Path Algorithm and I have also added a unit test to test the logic in the test directory.
I did an additional pass over the edges and if there is any change detected ,An Invalid Argument exception is thrown.
"A Negative cycle has been detected in the graph".The unit test checks if this exception is thrown for a negative cycle and all the tests are passed too.

Added the negative cycle detection in bellman ford

---

README.md

In this PR I fixed the formatting of the entry and while i was there I change the order of the algorithm categories such that they are in alphabetical order.

fixed formatting in readme and changed the order to alphabetical

---

test/utils/scenarios/scenarios.h
test/utils/scenarios/scenarios.tpp

[TEST] Scenarios for fully connected and disconnected graphs

---

README.md

@bobluppes  I believe we need to make 2 more things:
- Guide for other OS users like Window and MacOS. If possible you should try and see how you would do it in Window OS. It was really tough for me.
- Easier, straightforward examples in installation guide. I checked the examples, maybe we need something that when we run it prints out something. Or maybe that's unnecessary because people don't use this library to print stuff but to calculate difficult algorithms

added environment set up link

---

include/graaflib/algorithm/utils.h
include/graaflib/algorithm/utils.tpp
include/graaflib/graph.h
include/graaflib/graph.tpp
test/graaflib/algorithm/utils_test.cpp
test/graaflib/graph_test.cpp

**CHANGES**
* New overload for `add_vertex()` in the `graph` class has been added that allows user to specify an ID for a given vertex. 
* `get_transposed_graph()` function has been added, allowing the user to get a transposed version of a particular directed graph. 
* Both functions have a javadoc style comment explaining the interface.
* Tests have been added to both functions.
Note: There does not seem to be a section in the documentation explaining the `graph` interface generally outside of the Quickstart guide, so I have not made any changes to the documentation. However, if something like this is required I would be happy to make additions. 
If you would like me to make any changes please do let me know.

Adding new utils header containing "get_transposed_graph" function

---

README.md
docs/docs/algorithms/strongly-connected-components/kosarajus.md
docs/docs/algorithms/strongly-connected-components/tarjan.md
include/graaflib/algorithm/strongly_connected_components/common.h
include/graaflib/algorithm/strongly_connected_components/kosaraju.h
include/graaflib/algorithm/strongly_connected_components/kosaraju.tpp
include/graaflib/algorithm/strongly_connected_components/tarjan.h
include/graaflib/algorithm/strongly_connected_components/tarjan.tpp
test/graaflib/algorithm/strongly_connected_components/kosaraju_test.cpp
test/graaflib/algorithm/strongly_connected_components/tarjan_test.cpp

Implements #115
&#x2611;  The algorithm is implemented
&#x2611;  The new function has a javadoc-style comment explaining the interface
&#x2611; Appropriate tests are added under `test/graaflib/algorithm/strongly_connected_components/kosarajus_test.cpp` 
&#x2611; A test coverage of at least 95% is reached
&#x2611; A documentation entry is added under `docs/docs/algorithms` under the appropriate category. Just adding a short description and the algorithm syntax here is fine. See the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) on how to build the documentation locally
&#x2611; The algorithm is added to the list of algorithms in `README.md`
I should flag here that I decided to use a simple recursive DFS - the one that was already in the library seemed …

[ALGO] Kosaraju's Algorithm

---

.github/workflows/pull-request.yml

Due to https://github.com/actions/runner-images/issues/8659, all of our CIs fail in the build stage for clang (see [here](https://github.com/bobluppes/graaf/actions/runs/6610675272/job/18094285713#step:4:1)  for example).
My recommendation would be dropping the clang build from the CI temporarily until the runner image is fixed. We would then test with g++ only. In the current CI config, the g++ does not even start if the clang fails.

[TEMP FIX] Remove clang build from CI

---

include/graaflib/graph.tpp
test/graaflib/graph_test.cpp

fix: Unexpected move when adding vertices and edges

---

tools/requirements.txt

Removes unnecessary Python dependencies. Will prevent dependabot from opening PRs like https://github.com/bobluppes/graaf/pull/188 and https://github.com/bobluppes/graaf/pull/191.

[TOOL] Clean Python dependencies

---

.gitignore
CMakeLists.txt
include/graaflib/algorithm/strongly_connected_components/tarjan.h

I tried to use FetchContent for CMake to install graaflib but it didn't work, after some testing I decided to create a fork.
I made a new interface with add_library and added the include directory over target_include_directories, when using FetchContent with these modifications, including graaflib worked.
I also made sure I could build and test the project so that this didn't break stuff, and I got a build error telling me that the tarjan test used std::sort as an unknown target, I added an include for <algorithm> in tarjan.h to make the project build and the tests ran at 100%
I'm not really acquainted with how you properly write CMakeList files so if there are any issues feel free to tell me.

CMake Targets for FetchContent

---

.github/workflows/pull-request.yml

Reverts #169. The root cause in the respective runner has been fixed recently (https://github.com/actions/runner-images/issues/9679).

[CI] Re-add clang to matrix build

---

docs/docs/quickstart/installation/installation.md

After creating targets for CMakes FetchContent in #217 I updated the documentation so that the shown target is correct.
So 
from `target_link_libraries(${PROJECT_NAME} PRIVATE Graaf_lib)` 
to `target_link_libraries(${PROJECT_NAME} PRIVATE Graaf::Graaf)`
I also added a section about the CMake Options that are available, and gave examples on how to use them when people include this library for their Project.
I verified the documentation building locally.

Updating Documentation for FetchContent Changes

---

test/graaflib/io/dot_test.cpp

It appears like CI runs for `DotTest` fail non-deterministically. See recent runs of the coverage CI:
- [PR-245](https://github.com/bobluppes/graaf/actions/runs/11777353577/job/32801585412?pr=245)
- [PR-246](https://github.com/bobluppes/graaf/actions/runs/11899516112/job/33158300868?pr=246)
- [PR-247](https://github.com/bobluppes/graaf/actions/runs/11891803869/job/33133311432?pr=247)
While I can't reproduce this locally, my suspicion is that multiple tests use `"./test.dot"` simultaneously, which then causes race conditions or file access conflicts due to concurrent write/read attempts to the same file path.
This PR provides a fix by making the filenames unique (683ed984ad624dad0d87bbf8741fcc4a63a7bfdf).
f826ab66d8ea36e7c7702a4447db9a1622c54b89 increases cross-platform compatibility and …

fix: Potential race for file access in DotTest

---

.github/workflows/main-ci.yml
.github/workflows/pull-request.yml

The coverage workflow was broken on ubuntu 24.04 machines. For now pinning the workflow to 22.04.

Fix coverage workflows

---

include/graaflib/algorithm/minimum_spanning_tree/kruskal.tpp

Previously the comparator of `edge_to_process` did not impose a strict weak ordering, resulting in undefined behavior when calling `std::sort`. I verified this with some very large input graphs but did not capture in a unit test.

kruskal: make edge comparator impose strict weak ordering
